aws-iot-builder-tools/aws-greengrass-provisioner

- README.md
- build.gradle
- docs/DeploymentCommandLine.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicConfigFileHelper.java
This commit switches from GG 1.6 bits to GG 1.7 bits and also adds the necessary configuration options for the MQTTServerCertificate, IoTCertificate, and SecretsManager configuration.
> Updates for GG 1.7.0

- .travis.yml
> Added Travis CI config

- src/main/java/com/awslabs/aws/greengrass/provisioner/data/SDK.java
Updated hashes and URLs for 1.3 SDKs for #8 
> New filenames and hashes for SDK 1.3

- src/main/resources/shell/template.sh.in
For #16 
cgroup bootstrapping fixed
> Fix cgroup bootstrapping on pi

- .gitignore
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
> Root ca rename

- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/AbstractDockerHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/GreengrassDockerHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/interfaces/DockerHelper.java
Fixed incorrect handling of stopped containers for #28 
> Fixed incorrect handling of stopped containers for #28

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupUpdateHelper.java
Fixes #37, commit incorrectly states it is a fix for #7 though
> Fix for #37

- docs/CommandLine.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/EcrDockerHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/OfficialGreengrassImageDockerHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/interfaces/EcrDockerClientProvider.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/interfaces/OfficialGreengrassImageDockerClientProvider.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GGConstants.java
Minor cleanup of Docker related code
> Use official docker container only

- src/main/resources/shell/template.sh.in
> NodeJS installation check now looks for nodejs6.10 executable

- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
Switched to the Greengrass 1.8.0 binaries
> Switched to Greengrass 1.8.0 binaries

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
> Added missing "Auth fail" test to SSH code

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
> Updated URLs to the latest 1.8.0 version of IDT

- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisioner.java
> Fix aws-greengrass-provisioner-65, better logging and forced JVM exit

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
> Aws greengrass provisioner 66

- README.md
- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
> Switched to Greengrass 1.8.1

- Dockerfile.build
- Dockerfile.run
- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/DeviceTesterLogMessageType.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/clientproviders/AwsCredentialsProvider.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeviceTesterHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicProcessHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicTestArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
- src/test/java/DeviceTesterMessageParsingTest.java
> Aws greengrass provisioner 62

- Dockerfile.run
Added npm to container and fixed #78 
> Added npm to container

- Dockerfile.build
- testing/build-loop.sh
- testing/integration-test.sh
- testing/push-to-dockerhub.sh
> Integration tests

- Dockerfile.run
- README.md
- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Language.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/SDK.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicNodeBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicTestArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/builders/ScriptingFunctionBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/FunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/LambdaHelper.java
> Moved to Greengrass 1.9.0 and Device Tester 1.3

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java
- testing/integration-test.sh
> Fix broken pip

- README.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/interfaces/OfficialGreengrassImageDockerClientProvider.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ArgumentHelper.java
Minor fixes I didn't want to include in the 1.9.1 update
> Minor fixes

- src/integration-test/java/GreengrassDeploymentsIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/FunctionConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicNodeBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/builders/ScriptingFunctionBuilder.java
Also added new integration tests to cover building a Node function with dependencies
> Dependencies for all languages are now resolved with standard methods

- build.sh
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGVariables.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
> Add ATS support

- build.gradle
- src/integration-test/java/GreengrassEndToEndIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/KeysAndCertificate.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicJsonHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/KeysAndCertificateSerializationTests.java
> Fix broken serialization/deserialization of credentials with Immutables

- build.gradle
- docs/DeploymentCommandLine.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/clientproviders/S3ClientProvider.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
> Put files in S3

- src/main/resources/shell/clean.sh.in
- src/main/resources/shell/template.sh.in
> Added missing call to daemon-reload after creating service

- build.gradle
- docs/DeploymentCommandLine.md
- src/integration-test/java/GreengrassEndToEndIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/QueryArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/TestArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/UpdateArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/resources/shell/template.sh.in
> Add bootstrapping support for non-EC2 systems

- build.gradle
- docs/QueryGroupCommandLine.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/QueryArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/OfficialGreengrassImageDockerHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicMavenBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/clientproviders/CloudWatchLogsClientProvider.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupQueryHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicSdkErrorHandler.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/SafeProvider.java
- testing/gradle-loop.sh
> Added download logs and watch logs features

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
> Cleaned up resource creation code and filtered functions running in no container mode from having resources created

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
> Build container now fails if GGP is running in Docker

- docs/QueryGroupCommandLine.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/QueryArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/DiagnosticRule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/FunctionTimedOutDiagnosticRule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/FunctionTimingOutDiagnosticRule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithJsonErrorDiagnosticRule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithJsonErrorDiagnosticRule1.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithJsonErrorDiagnosticRule2.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithTextErrorDiagnosticRule1.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithoutJsonDiagnosticRule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/NoConnectivityInformationDiagnosticRule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/TooManyIpsDiagnosticRule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDiagnosticsHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupQueryHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/DiagnosticsHelper.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/KeysAndCertificateSerializationTests.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/FunctionTimedOutDiagnosticRuleTest.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/FunctionTimingOutDiagnosticRuleTest.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithJsonErrorDiagnosticRule1Test.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithJsonErrorDiagnosticRule2Test.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithTextErrorDiagnosticRule1Test.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/NoConnectivityInformationDiagnosticRuleTest.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/TooManyIpsDiagnosticRuleTest.java
> Implemented diagnostics feature for Greengrass groups

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
> Fixes for #160

- README.md
- build.gradle
- src/integration-test/java/GreengrassEndToEndIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
> Moved to GG 1.9.2

- Dockerfile.run
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicTestArgumentHelper.java
Updated to use Device Tester 1.3.2
> Moved to Device Tester 1.3.2

- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/DeploymentConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java
> Implements shadow sync option for the Greengrass Core

- build.gradle
- docs/DeploymentCommandLine.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/EC2LinuxVersion.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/exceptions/SshRecoverableException.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ArgumentHelper.java
- src/main/resources/shell/template.sh.in
Fixes for #190, #191, #192, #193, and #194 
> Batch of a bunch of semi-related fixes

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
> Make service account association failures fatal

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
> Better error message for missing service role

- src/integration-test/java/GreengrassEC2ImagesIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
> Integration tests for EC2 image filters

- build.gradle
- docs/GettingStarted.md
- lambda-support/invoke-lambda-function.sh
- lambda-support/lambda-stack-for-ggp.yaml
- lambda-support/launch-lambda-stack-for-ggp.sh
- src/integration-test/java/ProvisionerLambdaIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/DeploymentConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIamHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IamHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/AwsGreengrassProvisionerLambda.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/LambdaInput.java
> Initial support for empty deployments with GGP as a Lambda function

- docs/DeploymentCommandLine.md
- src/integration-test/java/GreengrassITShared.java
- src/integration-test/java/ProvisionerLambdaIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/Arguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/UpdateArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/AwsGreengrassProvisionerLambda.java
> Keys are only regenerated if the user forces it to avoid breaking existing deployments

- src/main/resources/shell/template.sh.in
> Only setting --allow-releaseinfo-change for Raspbian Buster

- docs/DeploymentCommandLine.md
- lambda-support/invoke-lambda-function.sh
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/UpdateArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupQueryHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupUpdateHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/DeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IotHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/AwsGreengrassProvisionerLambda.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/LambdaInput.java
> GGP can now accept a CSR or a certificate ARN instead of generating new certificates

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
> Fail during EC2 launch if no usable SSH keys exist

- lambda-support/extract-from-outfile.sh
- lambda-support/ggp-config-for-cross-account-usage.yaml
- lambda-support/invoke-lambda-function.sh
- lambda-support/lambda-stack-for-ggp.yaml
- src/integration-test/java/ProvisionerLambdaIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/AwsGreengrassProvisionerLambda.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/LambdaInput.java
Addresses #320. Using environment variables the Lambda function can be invoked with cross-account credentials and create empty groups in a customer's account.
> Assume role for lambda

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IotHelper.java
> Fix csr issue

- README.md
- build.gradle
- src/integration-test/java/GreengrassEndToEndIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
> Updated to use Greengrass version 1.9.4

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
> Force pull of Greengrass container using the correct client

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicScriptHelper.java
- src/main/resources/shell/clean.sh.in
- src/main/resources/shell/install.sh.in
> Putting certificates and config files in a sub-directory in the OEM file and installation script

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicArchiveHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ArchiveHelper.java
> Added certs/core.crt.arn to install script and OEM file

- Dockerfile.build
- src/main/resources/shell/template.sh.in
This may break Python 2 functions in the function repo but those will be removed soon anyway
Fixes #384 
> Fix python 3.7 support for #384 and remove Python 2 related code

- Dockerfile.run
- docs/CommandLine.md
- docs/DeploymentCommandLine.md
- docs/HSIBootstrapCommandLine.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/HsiBootstrapArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/HsiParameters.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/HsiParametersConverter.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/HsiVendor.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicExecutableBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicConfigFileHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicHsiBootstrapArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicHsiBootstrapHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicSshHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/HsiBootstrapArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/HsiBootstrapHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/SshHelper.java
- src/main/resources/greengrass-hsi/bootstrap-common.sh
- src/main/resources/greengrass-hsi/bootstrap-softhsm2.sh
- src/main/resources/shell/credentials.sh
- src/main/resources/shell/template.sh.in
> Implement new HSI bootstrapping mechanism

- docs/CommandLine.md
- docs/Concepts.md
- docs/HSIBootstrapCommandLine.md
- docs/HowItWorks.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/HsiVendor.java
- src/main/resources/greengrass-hsi/bootstrap-zymbit.sh
> HSI support for Zymbit Zymkey 4i

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIamHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IamHelper.java
> Inline IAM policies weren’t set up

- Dockerfile.run
- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/FunctionConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalSecretsManagerResource.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/clientproviders/SecretsManagerClientProvider.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicSecretsManagerHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/SecretsManagerHelper.java
> Secrets manager support

- build.gradle
- src/integration-test/java/GreengrassEC2ImagesIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/test/java/SoftwareDownloadTest.java
Updated software list for Greengrass 1.10.0 and added a test to make sure the binaries are available
Fixes #411 
> Moved to Greengrass 1.10.0

- src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/docker/OfficialGreengrassImageDockerHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicConfigFileHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
> Aws greengrass provisioner 413

- Dockerfile.run
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicGradleBuilder.java
> Added missing protobuf dependency

- src/main/resources/shell/install.sh.in
- src/main/resources/shell/template.sh.in
Fixes #322 
Note: On some platforms Docker Compose is not available
> Docker and Docker Compose installation

- src/main/resources/shell/template.sh.in
- src/main/resources/shell/update-dependencies.sh.in
> Create ggc_user before running update dependencies script

- docs/Concepts.md
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Language.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
- src/main/resources/shell/update-dependencies.sh.in
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/FunctionTimingOutDiagnosticRuleTest.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithJsonErrorDiagnosticRule1Test.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithJsonErrorDiagnosticRule2Test.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/data/diagnostics/MissingRuntimeWithTextErrorDiagnosticRule1Test.java
> Migrate to NodeJS 12.x

- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisioner.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/ConnectorConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/Connectors.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/DeploymentConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/RoleConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicConnectorHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicEnvironmentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGDHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGVariables.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicResourceHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicS3Helper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicTypeSafeConfigHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ConnectorHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/EnvironmentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/FunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GGConstants.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GGVariables.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ResourceHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/S3Helper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/TypeSafeConfigHelper.java
> Added connector support

- Dockerfile.build
- Dockerfile.run
- src/integration-test/java/GreengrassBuildWithDockerDeploymentsIT.java
- testing/integration-test.sh
Move to Amazon Linux 2 and Corretto for Docker images
> Corretto build

- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/FunctionConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicEnvironmentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
> Aws greengrass provisioner 405

- docs/CommandLine.md
- src/integration-test/java/ProvisionerLambdaIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/DeploymentStatus.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/ConnectorConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/exceptions/IamReassociationNecessaryException.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicConnectorHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelperTest.java
This cleans up the error handling for deployments. The existing structure was getting hard to manage and extend.
> Better failsafe code

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicSubscriptionHelper.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/SubscriptionHelperTest.java
> Fix wildcard subscriptions

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
> Opening ports for functions on EC2

- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/DeploymentConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GGConstants.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java
> Loggers can now be configured

- src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalDeviceResource.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalReadOnlyOrReadWriteResource.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalResource.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalVolumeResource.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
> Do not filter out secrets from functions running outside of the Greengrass container

- build.gradle
- src/integration-test/java/ProvisionerLambdaIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/Injector.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupUpdateHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicScriptHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicSubscriptionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IotHelper.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/SubscriptionHelperTest.java
Moved more functionality into the results iterator library
> Moved more functionality into the results iterator library

- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/DeploymentConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/FunctionConf.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicExecutableBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicGradleBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicNodeBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicCloudFormationHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGVariables.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/builders/GradleBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/builders/ScriptingFunctionBuilder.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/LambdaHelper.java
- src/test/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/SubscriptionHelperTest.java
> More type safety updates

- src/main/java/com/awslabs/aws/greengrass/provisioner/data/KeysAndCertificate.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
> Key serialization issue

- README.md
- build.gradle
- src/integration-test/java/GreengrassEndToEndIT.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/Injector.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GGConstants.java
> Updated to Greengrass 1.10.1

- build.gradle
- src/main/java/com/awslabs/aws/greengrass/provisioner/data/FunctionConfAndFunctionCode.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/FunctionHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/LambdaHelper.java
Needed this when I started testing with Vaadin 15.
> Added support for uploading Lambda functions to S3 when they exceed the max direct upload size

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
Fixes #605, another bad string concatenation
> Fixes #605

- src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
- src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
Properties file was not being created and
the lambda reported a "Not Found" error.
*Issue #, if available:*
> Fix Properties File creation

- lambda-support/launch-lambda-stack-for-ggp.sh
Add the Profile when checking the status of the CFN.
*Issue #, if available:*
> Add profile when querying for CFN status

- Dockerfile.run
Fixes #811 
Thank you for reporting this!
> Kimsehwan96 bugfix/python builder python3 devel
