src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicConfigFileHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ConfigFileHelper.java

Added toggle to disable systemd.  systemd is enabled by default.  `--no-systemd` disables systemd support in config.json.

Added systemd toggle for #3

---

src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/FunctionHelper.java

This set of commits pulls the default container mode for the functions and then sets that default value in the function definition version.  It also automatically scrubs the memory size value from functions if they are set up to use the NoContainer isolation mode either explicitly or by inheriting the default.

Set default container option

---

src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
src/main/java/com/awslabs/aws/greengrass/provisioner/docker/AbstractDockerHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/docker/GreengrassDockerHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/docker/interfaces/DockerClientProvider.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicGradleBuilder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicMavenBuilder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicNodeBuilder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicCloudFormationHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGDHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupQueryHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupUpdateHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicResourceHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/builders/ScriptingFunctionBuilder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ExecutorHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IoHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/SafeProvider.java

RuntimeException makes more sense for these errors. They shouldn't be UnsupportedOperationExceptions.

Changed UnsupportedOperationExceptions to RuntimeExceptions

---

docs/DeploymentCommandLine.md
src/main/java/com/awslabs/aws/greengrass/provisioner/data/arguments/DeploymentArguments.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicConfigFileHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicJsonHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/ConfigFileHelper.java
src/main/resources/shell/template.sh.in

Added initial support for SoftHSM2.  Works on EC2 instances and local systems running Ubuntu.

Add hsi softhsm2 support

---

src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGConstants.java

Name of the official container changed, fixed.

Fix for #44 - Greengrass Docker image name updated

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/com/awslabs/aws/greengrass/provisioner/data/SDK.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicNodeBuilder.java

1.3.1 SDK for NodeJS was not working, this fixes that

Fixes for 1.3.1 sdks

---

build.gradle
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java

Fix for #55 
Also, added retries for security group visibility as an issue came up with that in testing.

Prevent failure to read SSH keys when .ssh directory contains subdirectories

---

.gitignore
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java

Cleaned up retry logic for Lambda IAM role checks with RetryPolicy instead of loops

Cleaner retry logic

---

src/main/resources/shell/template.sh.in

Fix aws-greengrass-provisioner-71, added retry and delay in bash script for package manager updates

---

Dockerfile.run

Gradle 5.4.1 is now part of the Docker container so Java builds are faster

---

README.md
build.gradle
src/integration-test/java/GreengrassDeploymentsIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/Architecture.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/Language.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java
src/main/resources/shell/template.sh.in

Updated to Greengrass 1.9.1. Some minor exception handling fixes. Set default NodeJS version to 8.10.0.

Greengrass 1.9.1 support

---

docs/DeploymentCommandLine.md
src/integration-test/java/GreengrassDeploymentsIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java

Fixed #92. `--ec2-launch` can now launch ARM64 instances.

Aws greengrass provisioner 92

---

Dockerfile.run
src/main/java/com/awslabs/aws/greengrass/provisioner/data/DeviceTesterLogMessageType.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeviceTesterHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicTestArgumentHelper.java
src/test/java/DeviceTesterMessageParsingTest.java

Fixes #106 
Adds a warning when the user may not have passwordless sudo set up on their Greengrass device under test

Updated to Device Tester 1.3.1

---

src/integration-test/java/GreengrassEndToEndIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/docker/AbstractDockerHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupUpdateHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/FunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java

This makes it easier to test with `--docker-launch`. With these changes the user doesn't have to modify their function.default.conf if they have greengrassContainer set to true but want to test with Docker.

Docker launch option overrides default function isolation mode

---

src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java

This update moves the Greengrass container default into the fallback configuration so it can be overridden.

Moved Greengrass container default into the fallback config

---

.gitignore
src/integration-test/java/GreengrassBuildWithDockerDeploymentsIT.java
src/integration-test/java/GreengrassBuildWithoutDockerDeploymentsIT.java
src/integration-test/java/GreengrassEndToEndIT.java
src/integration-test/java/GreengrassITShared.java
src/integration-test/java/GreengrassUpdateWithoutDockerIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisioner.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java

Fixes #156 
- Sets default isolation mode to no container or Greengrass container on each deploy
- Uses Greengrass container as the default isolation mode if it is not present

Fix issues with updating groups without a default container mode

---

src/main/java/com/awslabs/aws/greengrass/provisioner/data/KeysAndCertificate.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
src/test/java/com/awslabs/aws/greengrass/provisioner/data/KeysAndCertificateSerializationTests.java

Fixes #177 by changing the default to have the core's shadow synced. This does not add a feature to configure whether or not it is synced.

Set core shadow sync to true by default

---

Dockerfile.run
src/integration-test/java/GreengrassBuildWithDockerDeploymentsIT.java
src/integration-test/java/GreengrassBuildWithoutDockerDeploymentsIT.java
src/integration-test/java/GreengrassITShared.java
src/integration-test/java/GreengrassUpdateWithoutDockerIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/functions/BuildablePython2Function.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/functions/BuildablePython3Function.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPython2Builder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPython3Builder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/builders/Python2Builder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/builders/Python3Builder.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/FunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/LambdaHelper.java
src/main/resources/shell/template.sh.in

Fixes #186 
Python 2 and Python 3 builds now work even when pip3 dependencies are required.

Added Python 2 and 3 builders

---

src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/builders/BasicPythonBuilder.java

*Fixes: https://github.com/awslabs/aws-greengrass-provisioner/issues/450*
This PR copies top level directories of python lambda function correctly during creating lambda package in the local PC using GGP. 

Fix a bug top-level directories disappeared during packaging files of python lambda

---

src/integration-test/java/GreengrassBuildWithDockerDeploymentsIT.java
src/integration-test/java/GreengrassITShared.java
src/integration-test/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/DuplicateLocalResourceIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalDeviceResource.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalResource.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalS3Resource.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalSageMakerResource.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalVolumeResource.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassResourceHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassResourceHelper.java

Fixes #448 
Performs some validation and gives informative error messages if a user tries to do something that will be rejected by the cloud (e.g. a source path that has two different destination paths).

Allow reuse of volume resources across multiple Greengrass Lambda functions

---

src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
testing/integration-test.sh

Functions inside the Greengrass container can now run as any uid/gid

---

build.gradle
src/integration-test/java/GreengrassUpdateWithoutDockerIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/AwsGreengrassProvisionerModule.java
src/main/java/com/awslabs/aws/greengrass/provisioner/Injector.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupQueryHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupTestHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupUpdateHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GreengrassHelper.java
testing/integration-test.sh

Pulled a lot of logic out of GGP and into the results iterator library to reduce the amount of code in GGP and to make convenience functions available to other projects.

Migrate functions to library

---

src/main/resources/shell/update-dependencies.sh.in

Some Greengrass Lambda functions that are in development, in particular the LLRP functions, cause OpenJDK's JRE 8 to crash. This update uses OpenJDK's JRE 11, which doesn't crash, and symlinks it to java8 so Greengrass can use it.

Moved Debian/Raspbian/Ubuntu installations to OpenJDK JRE 11 due to OpenJDK JRE 8 instabilities

---

src/integration-test/java/GreengrassEndToEndIT.java
src/main/java/com/awslabs/aws/greengrass/provisioner/data/conf/FunctionConf.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentArgumentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicFunctionHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicTypeSafeConfigHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/TypeSafeConfigHelper.java

uid and gid are now optional in the function configuration. If they are not specified they default to the ggc_user/ggc_group.

Only setting runAs values if they are specified by the user

---

build.gradle
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicDeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGGVariables.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGroupUpdateHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIotHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/DeploymentHelper.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/GGVariables.java
src/main/java/com/awslabs/aws/greengrass/provisioner/interfaces/helpers/IotHelper.java

Integration tests already passed

Cleaned up credential output code, also creating iotcp.properties for results iterator library for each deployment

---

src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/AwsGreengrassProvisionerLambda.java
src/main/java/com/awslabs/aws/greengrass/provisioner/lambda/LambdaInput.java

Add the ability to specify region along
with AWS Creds so that the IoT resources
are created in the appropriate AWS region.
*Issue #, if available:*

Add Region Support for Provisioner Lambda

---

Dockerfile.run

Fixes: #811 
Add a commandline for installing python3-devel.x86_64 in Dockerfile.run
Installing some python packages need to be installed `python3-devel.x86_64` in the machine.
So I add `yum install -y python3-devel.x86_64` in `Dockerfile.run`

Add commandline for installing python3-devel.x86_64 in Dockerfile.run

---

src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java

Lambda functions can now report that they are in a pending state. The existing logic didn't handle this.
This was reported in #970 but initial testing of the fix wasn't successful.
After further research it appears that #970 addresses the pending state issue when an existing function is updated but not when a new function is created.
The solution was to modify the LambdaClient calls to updateFunctionCode, createFunction, and updateFunctionConfiguration by wrapping them in a failsafe executor that handles IAM propagation delays as well as the Lambda pending function state.

Using a failsafe executor to deal with Lambda API paths that can return that a function is in the pending state
